<a href="https://colab.research.google.com/github/tylerasteele/LinearAlgebraProjects/blob/main/DeterminantWorksheets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

test = np.matrix([[12, 13, 12],
                  [5, 0, 4],
                  [1, 2, 3]])

np.linalg.det(test)

-118.99999999999993

In [ ]:
a = np.matrix([[10, 7],
               [8 , 9]])
b = np.matrix([[-10, -1],
               [-4 , 7]])
c = np.matrix([[1, -3],
               [7 , 7]])


#print (a*b,"\n\n", b*a)
#print (np.linalg.det(a*b), "\n\n", np.linalg.det(b*a))

#print (a*c,"\n\n", c*a)
#print (np.linalg.det(a*c), "\n\n", np.linalg.det(c*a))

print (b*c,"\n\n", c*b)
print (np.linalg.det(b*c), "\n\n", np.linalg.det(c*b))



[[-17  23]
 [ 45  61]] 

 [[  2 -22]
 [-98  42]]
-2071.9999999999995 

 -2071.9999999999995


In [ ]:
print(np.linalg.det(a*b*c), "\n", np.linalg.det(a*c*b), "\n",np.linalg.det(c*b*a) )

-70447.99999999994 
 -70447.99999999994 
 -70447.99999999994


In [19]:
A = np.matrix([[3, 2, 3],
               [-6, 1, -10],
               [-8, -9, -9]])
B = np.matrix([[1, -2, 1],
                [5, 5, 4],
                [4, 0, 0]])
C = np.matrix([[1, 0, 0], 
                [0, 2, 0],
                [-3, -2, 1]])

#print (A*B,"\n\n", B*A)
#print (np.linalg.det(A*B), "\n\n", np.linalg.det(B*A))

#print (A*C,"\n\n", C*A)
#print (np.linalg.det(A*C), "\n\n", np.linalg.det(C*A))

#print (B*C,"\n\n", C*B)
#print (np.linalg.det(B*C), "\n\n", np.linalg.det(C*B))


[[-2 -6  1]
 [-7  2  4]
 [ 4  0  0]] 

 [[  1  -2   1]
 [ 10  10   8]
 [ -9  -4 -11]]
-103.99999999999999 

 -104.00000000000007


In [20]:
print(np.linalg.det(A*B*C), "\n", np.linalg.det(A*C*B), "\n",np.linalg.det(C*B*A) )

6135.999999999995 
 6136.000000000006 
 6136.000000000006
